"""katsi core package."""

# Re-export key multimedia contracts for convenience
from katsi_core.media.contracts import (
    DerivedRepresentation,
    EvidenceLocatorUnion,
    ImageRegionLocator,
    MediaDescriptor,
    MediaProcessingConfig,
    MediaRepresentationKind,
    MediaRepresentationStatus,
    MediaTypeFamily,
    PageLocator,
    SceneLocator,
    TextRangeLocator,
    TimeRangeLocator,
    VideoFrameLocator,
    WholeResourceLocator,
    chunk_to_representation,
    extraction_to_representation,
)
from katsi_core.workspace import (
    ActionOutcome,
    AgentIdentity,
    AuthorizationDeniedError,
    CapabilityGrant,
    ChangeSet,
    ChangeSetService,
    ChangeSetTransition,
    Claim,
    ConflictError,
    InvalidTransitionError,
    PortableProjectState,
    PortableStateStore,
    ProjectionLagError,
    RecoveryRequiredError,
    Resource,
    ResourceVersion,
    StaleStateError,
    UnsupportedOperationError,
    WorkLease,
    Workspace,
    WorkspaceError,
    WorkspaceEvent,
)

__version__ = "0.1.0"

__all__ = [
    "ActionOutcome",
    "AgentIdentity",
    "AuthorizationDeniedError",
    "CapabilityGrant",
    "ChangeSet",
    "ChangeSetService",
    "ChangeSetTransition",
    "Claim",
    "ConflictError",
    "InvalidTransitionError",
    "ProjectionLagError",
    "PortableProjectState",
    "PortableStateStore",
    "RecoveryRequiredError",
    "Resource",
    "ResourceVersion",
    "StaleStateError",
    "UnsupportedOperationError",
    "WorkLease",
    "Workspace",
    "WorkspaceError",
    "WorkspaceEvent",
    # Multimedia contracts
    "DerivedRepresentation",
    "EvidenceLocatorUnion",
    "ImageRegionLocator",
    "MediaDescriptor",
    "MediaProcessingConfig",
    "MediaRepresentationKind",
    "MediaRepresentationStatus",
    "MediaTypeFamily",
    "PageLocator",
    "SceneLocator",
    "TextRangeLocator",
    "TimeRangeLocator",
    "VideoFrameLocator",
    "WholeResourceLocator",
    "chunk_to_representation",
    "extraction_to_representation",
]
