"""Authoritative workspace coordination contracts and errors."""

from katsi_core.workspace.brief import BriefService
from katsi_core.workspace.change_sets import ChangeSetService
from katsi_core.workspace.claims import ClaimService
from katsi_core.workspace.contracts import (
    ActionOutcome,
    ActionOutcomeStatus,
    AgentIdentity,
    BriefClaim,
    BriefLease,
    BriefOpenWork,
    BriefRecentEvent,
    BriefRecord,
    BriefSection,
    CapabilityGrant,
    CapabilityOperationClass,
    ChangeSet,
    ChangeSetStatus,
    ChangeSetTransition,
    Claim,
    ClaimEvidence,
    ClaimEvidenceKind,
    ClaimStatus,
    ClaimTransition,
    OmittedSection,
    OpenWork,
    OpenWorkStatus,
    OpenWorkTransition,
    PortableProjectState,
    ProjectionFreshness,
    Resource,
    ResourceDependency,
    ResourceStatus,
    ResourceVersion,
    RiskClass,
    WorkLease,
    WorkLeaseKind,
    WorkLeaseStatus,
    Workspace,
    WorkspaceBrief,
    WorkspaceEvent,
    WorkspaceEventKind,
    WorkspaceRecord,
    WorkspaceRecordKind,
    WorkspaceRecordStatus,
    WorkspaceRecordTransition,
    WorkspaceStatus,
)
from katsi_core.workspace.errors import (
    AuthorizationDeniedError,
    ConflictError,
    InvalidTransitionError,
    ProjectionLagError,
    RecoveryRequiredError,
    StaleStateError,
    UnsupportedOperationError,
    WorkspaceError,
)
from katsi_core.workspace.identity import IdentityService, IssuedCredential
from katsi_core.workspace.intent import IntentService
from katsi_core.workspace.leases import WorkLeaseService
from katsi_core.workspace.observer import (
    FilesystemEvent,
    FilesystemEventKind,
    FilesystemObserver,
    WatchdogObserver,
    WorkspaceScanner,
)
from katsi_core.workspace.portable_state import PortableStateStore
from katsi_core.workspace.records import WorkspaceRecordService

__all__ = [
    "ActionOutcome",
    "ActionOutcomeStatus",
    "AgentIdentity",
    "AuthorizationDeniedError",
    "BriefClaim",
    "BriefLease",
    "BriefOpenWork",
    "BriefRecentEvent",
    "BriefRecord",
    "BriefSection",
    "BriefService",
    "CapabilityGrant",
    "CapabilityOperationClass",
    "ChangeSet",
    "ChangeSetStatus",
    "ChangeSetTransition",
    "Claim",
    "ClaimEvidence",
    "ClaimEvidenceKind",
    "ClaimStatus",
    "ClaimTransition",
    "ConflictError",
    "InvalidTransitionError",
    "ProjectionLagError",
    "PortableProjectState",
    "PortableStateStore",
    "IdentityService",
    "IssuedCredential",
    "IntentService",
    "WorkLeaseService",
    "ClaimService",
    "ChangeSetService",
    "FilesystemEvent",
    "FilesystemEventKind",
    "FilesystemObserver",
    "WatchdogObserver",
    "WorkspaceScanner",
    "OpenWork",
    "OpenWorkStatus",
    "OpenWorkTransition",
    "OmittedSection",
    "RecoveryRequiredError",
    "Resource",
    "ResourceDependency",
    "ResourceStatus",
    "ResourceVersion",
    "RiskClass",
    "StaleStateError",
    "UnsupportedOperationError",
    "WorkLease",
    "WorkLeaseKind",
    "WorkLeaseStatus",
    "Workspace",
    "WorkspaceBrief",
    "WorkspaceRecord",
    "WorkspaceRecordKind",
    "WorkspaceRecordService",
    "WorkspaceRecordStatus",
    "WorkspaceRecordTransition",
    "WorkspaceError",
    "WorkspaceEvent",
    "WorkspaceEventKind",
    "WorkspaceStatus",
    "ProjectionFreshness",
]
