"""Authoritative workspace coordination contracts and errors."""

# ruff: noqa: F401

from katsi_core.workspace.action_journal import ActionJournalService
from katsi_core.workspace.authorization import (
    AuthorizationResult,
    AuthorizationService,
    PolicyMode,
)
from katsi_core.workspace.brief import BriefService
from katsi_core.workspace.change_sets import ChangeSetService
from katsi_core.workspace.claims import ClaimService
from katsi_core.workspace.contracts import (
    ActionOutcome,
    ActionOutcomeId,
    ActionOutcomeStatus,
    AgentIdentity,
    AgentIdentityId,
    ApplyPatchOperation,
    BriefClaim,
    BriefLease,
    BriefOpenWork,
    BriefRecentEvent,
    BriefRecord,
    BriefSection,
    CapabilityGrant,
    CapabilityGrantId,
    CapabilityOperationClass,
    ChangeSet,
    ChangeSetId,
    ChangeSetStatus,
    ChangeSetTransition,
    ChangeSetTransitionId,
    Claim,
    ClaimEvidence,
    ClaimEvidenceKind,
    ClaimStatus,
    ClaimTransition,
    ContentHash,
    CopyFileOperation,
    CreateDirectoryOperation,
    CreateFileOperation,
    DerivedMediaOperationBase,
    ExportKeyframesOperation,
    ExportRepresentationOperation,
    ExportTranscriptOrOcrOperation,
    GenerateProxyMediaOperation,
    GenerateThumbnailOperation,
    MoveFileOperation,
    OmittedSection,
    OpenWork,
    OpenWorkStatus,
    OpenWorkTransition,
    Operation,
    PortableProjectState,
    ProjectionFreshness,
    QuarantineFileOperation,
    RelativePath,
    ReplaceDerivedArtifactOperation,
    ReplaceDerivedMediaArtifactOperation,
    ReplaceFileOperation,
    Resource,
    ResourceDependency,
    ResourceId,
    ResourceStatus,
    ResourceVersion,
    ResourceVersionId,
    RestoreQuarantinedFileOperation,
    RiskClass,
    WorkLease,
    WorkLeaseId,
    WorkLeaseKind,
    WorkLeaseStatus,
    Workspace,
    WorkspaceBrief,
    WorkspaceEvent,
    WorkspaceEventId,
    WorkspaceEventKind,
    WorkspaceId,
    WorkspaceRecord,
    WorkspaceRecordKind,
    WorkspaceRecordStatus,
    WorkspaceRecordTransition,
    WorkspaceStatus,
    YoloAuthorization,
    YoloMode,
    YoloModeStatus,
    YoloSuspensionEvent,
)
from katsi_core.workspace.errors import (
    AuthorizationDeniedError,
    ConflictError,
    InvalidTransitionError,
    ProjectionLagError,
    RecoveryRequiredError,
    StaleStateError,
    UnsupportedOperationError,
    WorkspaceError,
)
from katsi_core.workspace.exclusive_leases import ExclusiveLeaseService
from katsi_core.workspace.governed_executor import FaultInjector, GovernedExecutor
from katsi_core.workspace.idempotent_operations import IdempotentOperationService
from katsi_core.workspace.identity import IdentityService, IssuedCredential
from katsi_core.workspace.intent import IntentService
from katsi_core.workspace.leases import WorkLeaseService
from katsi_core.workspace.observer import (
    FilesystemEvent,
    FilesystemEventKind,
    FilesystemObserver,
    WatchdogObserver,
    WorkspaceScanner,
)
from katsi_core.workspace.operations import (
    CopyOperation,
    CreateOperation,
    DerivedArtifactReplaceOperation,
    DeterministicPatchOperation,
    DirectoryCreateOperation,
    ExactHashReplaceOperation,
    FilesystemOperationExecutor,
    ForbiddenOperationError,
    ForbiddenOperationType,
    InWorkspaceMoveOperation,
    OperationKind,
    OperationLimits,
    OperationResult,
    PathAttackType,
    PathSecurityConfig,
    PathValidationError,
    PreflightCheckResult,
    PreflightContext,
    QuarantineOperation,
    RestoreOperation,
    apply_patch_in_memory,
    compute_blake3_hash,
    compute_content_hash,
    create_operation_id,
    perform_preflight_checks,
    validate_operation_limits,
    validate_path_security,
)
from katsi_core.workspace.owner_api import (
    ChangeSetProposal,
    OwnerAPI,
    OwnerDecision,
)
from katsi_core.workspace.portable_state import PortableStateStore
from katsi_core.workspace.quarantine import QuarantineRecord, QuarantineService
from katsi_core.workspace.records import WorkspaceRecordService
from katsi_core.workspace.recovery_store import RecoveryBlobStore
from katsi_core.workspace.staging import AdjacentStagingManager
from katsi_core.workspace.staleness import (
    StalenessService,
    StaleTrigger,
)
from katsi_core.workspace.validation import (
    ValidationResult,
    ValidationService,
)
from katsi_core.workspace.yolo import (
    PolicySimulationResult,
    YoloActivationResult,
    YoloService,
    YoloSuspensionReason,
)

__all__ = [
    "ActionOutcome",
    "ActionOutcomeStatus",
    "AgentIdentity",
    "AgentIdentityId",
    "AuthorizationDeniedError",
    "BriefClaim",
    "BriefLease",
    "BriefOpenWork",
    "BriefRecentEvent",
    "BriefRecord",
    "BriefSection",
    "BriefService",
    "CapabilityGrant",
    "CapabilityOperationClass",
    "ChangeSet",
    "ChangeSetStatus",
    "ChangeSetTransition",
    "Claim",
    "ClaimEvidence",
    "ClaimEvidenceKind",
    "ClaimStatus",
    "ClaimTransition",
    "ConflictError",
    "InvalidTransitionError",
    "ProjectionLagError",
    "PortableProjectState",
    "PortableStateStore",
    "IdentityService",
    "IssuedCredential",
    "IntentService",
    "WorkLeaseService",
    "ClaimService",
    "ChangeSetService",
    "FilesystemEvent",
    "FilesystemEventKind",
    "FilesystemObserver",
    "WatchdogObserver",
    "WorkspaceScanner",
    "OpenWork",
    "OpenWorkStatus",
    "OpenWorkTransition",
    "OmittedSection",
    "RecoveryRequiredError",
    "Resource",
    "ResourceDependency",
    "ResourceStatus",
    "ResourceVersion",
    "RiskClass",
    "StaleStateError",
    "UnsupportedOperationError",
    "WorkLease",
    "WorkLeaseKind",
    "WorkLeaseStatus",
    "Workspace",
    "WorkspaceBrief",
    "WorkspaceRecord",
    "WorkspaceRecordKind",
    "WorkspaceRecordService",
    "WorkspaceRecordStatus",
    "WorkspaceRecordTransition",
    "WorkspaceError",
    "WorkspaceEvent",
    "WorkspaceEventKind",
    "WorkspaceStatus",
    "ProjectionFreshness",
    "YoloAuthorization",
    "YoloMode",
    "YoloModeStatus",
    "YoloSuspensionEvent",
    "YoloService",
    "YoloActivationResult",
    "PolicySimulationResult",
    "YoloSuspensionReason",
    "AuthorizationResult",
    "AuthorizationService",
    "PolicyMode",
    "ValidationResult",
    "ValidationService",
    "StaleTrigger",
    "StalenessService",
    "ChangeSetProposal",
    "OwnerAPI",
    "OwnerDecision",
]
